// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN3IBnceiy2uKdQDM39uXBAgkOgIaJYrM',
    appId: '1:699921010569:web:2771dad63dc2ee672c5b58',
    messagingSenderId: '699921010569',
    projectId: 'healthlab-847e7',
    authDomain: 'healthlab-847e7.firebaseapp.com',
    storageBucket: 'healthlab-847e7.firebasestorage.app',
    measurementId: 'G-8SR96SMRTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG7kCye0p1G3MFgMvaelnqsigCWu8nN0g',
    appId: '1:699921010569:android:0e0d25c9f6ab505a2c5b58',
    messagingSenderId: '699921010569',
    projectId: 'healthlab-847e7',
    storageBucket: 'healthlab-847e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNw5KMR2aSaXlsoSDyQL81szNeHsjTaco',
    appId: '1:699921010569:ios:8b7e5d88794eb3ac2c5b58',
    messagingSenderId: '699921010569',
    projectId: 'healthlab-847e7',
    storageBucket: 'healthlab-847e7.firebasestorage.app',
    iosBundleId: 'com.example.healthlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNw5KMR2aSaXlsoSDyQL81szNeHsjTaco',
    appId: '1:699921010569:ios:8b7e5d88794eb3ac2c5b58',
    messagingSenderId: '699921010569',
    projectId: 'healthlab-847e7',
    storageBucket: 'healthlab-847e7.firebasestorage.app',
    iosBundleId: 'com.example.healthlab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN3IBnceiy2uKdQDM39uXBAgkOgIaJYrM',
    appId: '1:699921010569:web:db00e57cb21010332c5b58',
    messagingSenderId: '699921010569',
    projectId: 'healthlab-847e7',
    authDomain: 'healthlab-847e7.firebaseapp.com',
    storageBucket: 'healthlab-847e7.firebasestorage.app',
    measurementId: 'G-69RNMWZEHL',
  );
}
